### ISSUE TITLE
SPRDPL submodule configuration broken

### ISSUE THREAD

**Issue by markoshorro** [zwegner/x86-sat#1]
The submodule [sprdpl](https://github.com/zwegner/sprdpl) included seems to have its configuration broken. According to `.git/config`, the only submodule is:

```
[submodule]
        active = .
```

Even cloning with `--recursive` or initializing submodules afterwards.

**Comment by zwegner** [comment]
Thanks for the report! Looks like I broke it when I moved the x86_sat code to a subdirectory in the repo, should be fixed now.
